// Seven named BI dashboards, each triggered by matching the user's typed query
// against a set of aliases below. Unlike the free-form "Ask about your data"
// flow, these are NOT generated by the LLM — they're built directly in code
// from the same read-only snapshot (see analyticsSnapshot.js), because a
// structured multi-metric dashboard needs to be exactly right every time, not
// assembled freshly by a language model from a huge JSON blob on each request.
// If a query doesn't match one of these, the caller falls through to the
// normal LLM-based analytics flow untouched.

const DASHBOARDS = [
  { key: 'command_centre', aliases: ['command centre', 'command center'] },
  { key: 'geographic_performance', aliases: ['geographic performance', 'geo performance', 'state district performance'] },
  { key: 'peak_mau_war_room', aliases: ['peak mau war room', 'mau war room', 'war room'] },
  { key: 'am_command_centre', aliases: ['account manager command centre', 'account manager command center', 'am command centre', 'am command center', 'admin command centre'] },
  { key: 'school_360', aliases: ['school 360', 'school 360°', 'school three sixty'] },
  { key: 'engagement_dashboard', aliases: ['teacher and student engagement', 'teacher & student engagement', 'engagement dashboard', 'student engagement dashboard'] },
  { key: 'risk_action_centre', aliases: ['risk and action centre', 'risk & action centre', 'risk action centre', 'risk and action center'] },
];

const matchDashboardQuery = (rawQuery) => {
  const q = (rawQuery || '').trim().toLowerCase();
  if (!q) return null;

  // Exact match first, across ALL dashboards, before any substring check —
  // otherwise a short generic alias ("command centre") can swallow a longer,
  // more specific one that happens to contain it as a substring ("account
  // manager command centre"), just because it's earlier in the DASHBOARDS list.
  for (const d of DASHBOARDS) {
    if (d.aliases.includes(q)) return d.key;
  }

  // Substring match, preferring the LONGEST matching alias (most specific) —
  // same reasoning: "account manager command centre" should win over "command
  // centre" when both are substrings of the typed query.
  let best = null, bestLen = 0;
  DASHBOARDS.forEach(d => {
    d.aliases.forEach(a => {
      if (q.includes(a) && a.length > bestLen) { best = d.key; bestLen = a.length; }
    });
  });
  return best;
};

const pct1 = (v) => (v == null ? 'N/A' : `${v}%`);
const num  = (v) => (v == null ? 0 : v);

// ── 1. Command Centre ───────────────────────────────────────────────────────
const buildCommandCentre = (snap) => {
  const t = snap.totals;
  const poeRow = (snap.overallActivityCompletionPct || []).find(a => a.activity === 'POE Submitted');
  const rows = [
    ['Total Schools', String(t.schools)],
    ['Total Students (Registered)', String(t.students)],
    ['Total Teachers (Registered)', String(t.teachers)],
    ['Adobe IDs Created', String(num(t.studentActivityParticipation?.adobeIdCreated?.participated))],
    ['Adobe IDs Activated', String(num(t.studentActivityParticipation?.adobeIdActivated?.participated))],
    [`MAU Participation (${snap.currentQuarter.toUpperCase()})`, pct1(t.mauQuarterlyPct?.[snap.currentQuarter])],
    [`CPD Completion (${snap.currentQuarter.toUpperCase()})`, pct1(t.cpdQuarterlyPct?.[snap.currentQuarter])],
    ['Hackathon Participation', pct1(t.studentActivityParticipation?.hackathonParticipated?.pct)],
    ['POE Submitted (schools)', pct1(poeRow?.yesPercent)],
    ['Green Schools', String(t.greenSchools)],
    ['Amber Schools', String(t.amberSchools)],
    ['Red Schools', String(t.redSchools)],
  ];
  const scoped = snap.scope === 'admin';
  const answer = `Command Centre — ${scoped ? 'snapshot of your assigned schools' : 'platform-wide snapshot'} as of now:\n`
    + `- ${t.schools} schools, ${t.students} registered students, ${t.teachers} registered teachers.\n`
    + `- ${num(t.studentActivityParticipation?.adobeIdCreated?.participated)} Adobe IDs created, ${num(t.studentActivityParticipation?.adobeIdActivated?.participated)} activated.\n`
    + `- MAU ${pct1(t.mauQuarterlyPct?.[snap.currentQuarter])}, CPD ${pct1(t.cpdQuarterlyPct?.[snap.currentQuarter])}, Hackathon ${pct1(t.studentActivityParticipation?.hackathonParticipated?.pct)}, POE ${pct1(poeRow?.yesPercent)} — all as % of REGISTERED (tracked) students/teachers/schools.\n`
    + `- Health mix: ${t.greenSchools} Green, ${t.amberSchools} Amber, ${t.redSchools} Red.`;
  return { answer, visualization: { type: 'table', title: scoped ? 'Command Centre — Your Schools' : 'Command Centre', columns: ['Metric', 'Value'], rows } };
};

// ── 2. Geographic Performance ───────────────────────────────────────────────
const buildGeographicPerformance = (snap) => {
  const rows = [...snap.byDistrict]
    .sort((a, b) => (a.state === b.state ? b.schools - a.schools : a.state.localeCompare(b.state)))
    .slice(0, 60)
    .map(d => [
      d.state, d.district, String(d.schools), String(d.students), String(d.teachers),
      pct1(d.mauQuarterlyPct?.[snap.currentQuarter]), pct1(d.cpdQuarterlyPct?.[snap.currentQuarter]),
      String(d.greenSchools), String(d.amberSchools), String(d.redSchools),
    ]);
  const topState = [...snap.byState].sort((a, b) => b.schools - a.schools)[0];
  const answer = `Geographic Performance — State → District drill-down (${snap.byDistrict.length} districts across ${snap.byState.length} states). `
    + (topState ? `${topState.state} has the most schools (${topState.schools}). ` : '')
    + `For an individual school's numbers, ask about that school by name or open it from the Schools page.`;
  return {
    answer,
    visualization: { type: 'table', title: 'Geographic Performance (State → District)', columns: ['State', 'District', 'Schools', 'Students', 'Teachers', 'MAU %', 'CPD %', 'Green', 'Amber', 'Red'], rows },
  };
};

// ── 3. Peak MAU War Room ────────────────────────────────────────────────────
const buildMauWarRoom = (snap) => {
  const t = snap.totals;
  const actual = t.mauQuarterlyPct?.[snap.currentQuarter];
  const gap = snap.studentsMissedLatestMau.length;
  const rate = t.mauDailyRunRate;
  const trackedSchools = snap.schools.filter(s => s.studentCount > 0);
  const priority = [...trackedSchools]
    .sort((a, b) => (a.mauQuarterlyPct?.[snap.currentQuarter] ?? 0) - (b.mauQuarterlyPct?.[snap.currentQuarter] ?? 0))
    .slice(0, 10)
    .map(s => {
      const donePct = s.mauQuarterlyPct?.[snap.currentQuarter] ?? 0;
      const stillNeeded = Math.round(s.studentCount * (1 - donePct / 100));
      return [s.schoolName, s.state, String(s.studentCount), pct1(donePct), String(stillNeeded)];
    });

  const qoq = snap.mauQoQ;
  const trendLine = qoq.comparable
    ? (qoq.declined.length > qoq.improved.length ? 'more schools declined than improved Q-o-Q' : qoq.improved.length > qoq.declined.length ? 'more schools improved than declined Q-o-Q' : 'roughly even split of schools improving vs declining Q-o-Q')
    : 'not enough elapsed quarters yet this fiscal year to compare';

  const answer = `Peak MAU War Room:\n`
    + `- Actual: ${pct1(actual)} of ${t.students} registered students have done MAU this quarter (${snap.currentQuarter.toUpperCase()}).\n`
    + `- Target: 100% of registered students (this system has no separate numeric target field, so 100% of registered is the assumed goal).\n`
    + `- Gap: ${gap} students still need to complete this quarter's MAU session to hit that target.\n`
    + `- Daily run rate: ${rate != null ? `${rate >= 0 ? '+' : ''}${rate} students/day, averaged over the recorded history window` : snap.scope === 'admin' ? 'this run-rate figure is nationwide-only and not available in your scoped view' : 'not yet computable — day-by-day tracking only started today, check back once a few more days have accumulated'}.\n`
    + `- Forecast: this system has no trend-projection mechanism, so no specific end-of-quarter number is offered — the closest real signal is the quarter-on-quarter direction: ${trendLine}.\n`
    + `- Schools to activate next: the ${priority.length} lowest-MAU schools with real registered students are listed in the table below, worst first.`;
  return {
    answer,
    visualization: { type: 'table', title: 'Peak MAU War Room — Schools to Activate Next', columns: ['School', 'State', 'Registered Students', `MAU % (${snap.currentQuarter.toUpperCase()})`, 'Still Needed for 100%'], rows: priority },
  };
};

// ── 4. Account Manager Command Centre ───────────────────────────────────────
const buildAmCommandCentre = (snap) => {
  const rows = snap.byAdmin.map(a => {
    const theirSchools = snap.schools.filter(s => s.assignedAdmin?.email === a.email);
    const avgHealth = theirSchools.length
      ? Math.round((theirSchools.reduce((sum, s) => sum + (s.healthScore ?? 0), 0) / theirSchools.filter(s => s.healthScore != null).length) * 10) / 10
      : null;
    const green = theirSchools.filter(s => s.healthStatus === 'Green').length;
    const amber = theirSchools.filter(s => s.healthStatus === 'Amber').length;
    const red = theirSchools.filter(s => s.healthStatus === 'Red').length;
    const dcaisBehind = snap.schoolsCurrentlyDueDcaisMonth.filter(s => s.assignedAdmin?.email === a.email).length;
    const inQueue = snap.interventionQueue.filter(s => s.assignedAdmin?.email === a.email).length;
    return [
      a.name, a.score != null ? String(a.score) : 'N/A', a.status || 'N/A', String(theirSchools.length),
      avgHealth != null ? String(avgHealth) : 'N/A', String(green), String(amber), String(red),
      String(a.poePendingCount), String(dcaisBehind), String(inQueue),
    ];
  });
  const scoped = snap.scope === 'admin';
  const top = snap.byAdmin[0], bottom = snap.byAdmin[snap.byAdmin.length - 1];
  const answer = scoped
    ? `Your Account Manager scorecard:\n- Score: ${top?.score ?? 'N/A'} (${top?.status ?? 'N/A'}).\n- "DCAIS Behind" and "Intervention Schools" are counts of your own schools currently on those exception lists — a 0 is good.`
    : `Account Manager Command Centre — ${snap.byAdmin.length} admins.\n`
      + (top ? `- Highest score: ${top.name} at ${top.score}.\n` : '')
      + (bottom && bottom !== top ? `- Lowest score: ${bottom.name} at ${bottom.score ?? 'N/A'}.\n` : '')
      + `- "DCAIS Behind" and "Intervention Schools" are counts of that admin's own schools currently on those exception lists — a 0 is good.`;
  return {
    answer,
    visualization: { type: 'table', title: scoped ? 'Your Account Manager Scorecard' : 'Account Manager Command Centre', columns: ['Admin', 'Score', 'Status', 'Schools', 'Avg Health', 'Green', 'Amber', 'Red', 'POE Pending', 'DCAIS Behind', 'Intervention Queue'], rows },
  };
};

// ── 5. School 360° ───────────────────────────────────────────────────────────
const buildSchool360 = (snap) => {
  const rows = snap.schools.slice(0, 60).map(s => {
    const hc = s.healthComponents || {};
    const dcaisStatus = !s.dcaisTrackingStarted
      ? 'Not started'
      : (s.dcaisMonthsDue?.length ?? 0) === 0
        ? 'Caught up'
        : `Behind since ${s.nextDcaisMonthDue}`;
    return [
      s.schoolName, s.state,
      hc.dataReadiness?.percent != null ? `${hc.dataReadiness.percent}%` : 'N/A',
      hc.adobeId?.percent != null ? `${hc.adobeId.percent}%` : 'N/A',
      pct1(s.cpdQuarterlyPct?.[snap.currentQuarter]),
      pct1(s.mauQuarterlyPct?.[snap.currentQuarter]),
      s.activityFlags?.['Hackathon Participated'] || 'No',
      dcaisStatus,
      s.activityFlags?.['POE Submitted'] || 'No',
      s.healthStatus || 'N/A',
    ];
  });
  const answer = `School 360° — one row per school (${snap.schools.length} total, showing up to 60), covering Data Readiness, Adobe ID, CPD, MAU, Hackathon, Monthly DCAIS status, POE, and overall Health in one view. Percentages are of that school's own registered students/teachers.`;
  return {
    answer,
    visualization: { type: 'table', title: 'School 360°', columns: ['School', 'State', 'Data Readiness', 'Adobe ID', 'CPD %', 'MAU %', 'Hackathon', 'Monthly DCAIS', 'POE', 'Health'], rows },
  };
};

// ── 6. Teacher & Student Engagement ─────────────────────────────────────────
const buildEngagementDashboard = (snap) => {
  const t = snap.totals;
  const studentsDone = t.students - snap.studentsMissedLatestMau.length;
  const teachersDone = t.teachers - snap.teachersMissedLatestCpd.length;
  const rows = [
    ['Total Students Registered', String(t.students)],
    ['Total Teachers Registered', String(t.teachers)],
    [`Students Done MAU (${snap.currentQuarter.toUpperCase()})`, String(studentsDone)],
    [`Teachers Done CPD (${snap.currentQuarter.toUpperCase()})`, String(teachersDone)],
    ['Repeat Student Participants', `${t.studentsRepeatCount} (${pct1(t.studentsRepeatPct)})`],
    ['Repeat Teacher Participants', `${t.teachersRepeatCount} (${pct1(t.teachersRepeatPct)})`],
    ['Student Champions (all elapsed quarters)', String(snap.studentsQuarterlyMauComplete.length)],
    ['Teacher Champions (all elapsed quarters)', String(snap.teachersQuarterlyCpdComplete.length)],
    ['Inactive Students (missed latest MAU)', String(snap.studentsMissedLatestMau.length)],
    ['Inactive Teachers (missed latest CPD)', String(snap.teachersMissedLatestCpd.length)],
    ['Students — No Engagement Record Yet', String(t.studentsEngagementUnknown)],
    ['Teachers — No Engagement Record Yet', String(t.teachersEngagementUnknown)],
  ];
  const champNames = snap.studentsQuarterlyMauComplete.slice(0, 3).map(s => s.name).join(', ') || 'none yet';
  const inactiveNames = snap.studentsMissedLatestMau.slice(0, 3).map(s => s.name).join(', ') || 'none';
  const answer = `Teacher & Student Engagement:\n`
    + `- Champions (100% of elapsed quarters done) include: ${champNames}.\n`
    + `- Currently inactive (missed the latest quarter) include: ${inactiveNames}.\n`
    + `- "No Engagement Record Yet" means their row predates the record-update timestamp tracking — not the same as inactive, it's genuinely unknown.`;
  return { answer, visualization: { type: 'table', title: 'Teacher & Student Engagement', columns: ['Metric', 'Value'], rows } };
};

// ── 7. Risk & Action Centre ─────────────────────────────────────────────────
const buildRiskActionCentre = (snap) => {
  const rows = [];
  snap.interventionQueue.slice(0, 10).forEach(s => rows.push(['Low Health Score', 'High', s.schoolName, s.pendingAction || `Health score ${s.healthScore}`]));
  snap.schoolsStoppedDcaisParticipation.slice(0, 10).forEach(s => rows.push(['DCAIS Went Silent', 'High', s.schoolName, `Stopped after ${s.stoppedAfterMonth}`]));
  snap.schoolsCurrentlyDueDcaisMonth.filter(s => s.trackingStarted).slice(0, 10).forEach(s => rows.push(['DCAIS Behind', 'Medium', s.schoolName, `Due since ${s.monthDue}`]));
  snap.byAdmin.filter(a => a.poePendingCount > 0).forEach(a => rows.push(['POE Backlog', 'Medium', a.name, `${a.poePendingCount} school(s) pending: ${a.poePendingSchools.slice(0, 3).join(', ')}${a.poePendingSchools.length > 3 ? ', ...' : ''}`]));
  snap.mauQoQ.declined.slice(0, 8).forEach(s => rows.push(['MAU Declined Q-o-Q', 'Medium', s.schoolName, `${s.changePts}pts (${s.previousQuarter.toUpperCase()} ${s.previousQuarterPct}% → ${s.latestQuarter.toUpperCase()} ${s.latestQuarterPct}%)`]));
  snap.cpdQoQ.declined.slice(0, 8).forEach(s => rows.push(['CPD Declined Q-o-Q', 'Medium', s.schoolName, `${s.changePts}pts (${s.previousQuarter.toUpperCase()} ${s.previousQuarterPct}% → ${s.latestQuarter.toUpperCase()} ${s.latestQuarterPct}%)`]));
  (snap.teachersNotEngagedRecently || []).filter(t => t.daysSinceLastRecordUpdate > 60).slice(0, 10).forEach(t => rows.push(['Teacher Inactive 60+ Days', 'Low', `${t.name} (${t.schoolName})`, `${t.daysSinceLastRecordUpdate} days since record last updated`]));

  const severityRank = { High: 0, Medium: 1, Low: 2 };
  rows.sort((a, b) => severityRank[a[1]] - severityRank[b[1]]);
  const capped = rows.slice(0, 60);
  const highCount = rows.filter(r => r[1] === 'High').length;
  const medCount = rows.filter(r => r[1] === 'Medium').length;
  const lowCount = rows.filter(r => r[1] === 'Low').length;
  const answer = `Risk & Action Centre — ${rows.length} auto-generated exceptions from real tracked data (${highCount} High, ${medCount} Medium, ${lowCount} Low), sorted worst first. Each row is a school or admin currently on one of the existing exception lists (low health score, DCAIS gone silent or behind, POE backlog, declining MAU/CPD, or a teacher with no recent record update) — nothing here is a routine status report, only actual problems.`;
  return { answer, visualization: { type: 'table', title: 'Risk & Action Centre', columns: ['Type', 'Severity', 'School / Person', 'Detail'], rows: capped } };
};

const BUILDERS = {
  command_centre: buildCommandCentre,
  geographic_performance: buildGeographicPerformance,
  peak_mau_war_room: buildMauWarRoom,
  am_command_centre: buildAmCommandCentre,
  school_360: buildSchool360,
  engagement_dashboard: buildEngagementDashboard,
  risk_action_centre: buildRiskActionCentre,
};

const buildDashboard = (key, snapshot) => BUILDERS[key](snapshot);

module.exports = { matchDashboardQuery, buildDashboard, DASHBOARDS };
